#! /bin/sh

sxhkd &
panel &
$HOME/.config/polybar/launch.sh & 
feh --bg-fill $HOME/Pictures/Wallpapers/wallpaper.jpg 


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          3
bspc config normal_border_color "#ff00dd"
bspc config focused_border_color "#95ff00"

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 30

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a termite state=floating
bspc rule -a discord desktop=2
bspc rule -a spotify desktop=^2 follow=on
bspc rule -a xfe state=floating
bspc rule -a java state=floating
