#! /bin/sh
$HOME/.config/polybar/launch.sh --shapes & 
feh --bg-fill $HOME/Pictures/Wallpapers/wallpaper.jpg &
sxhkd &
polybar & 
xsetroot -cursor_name left_ptr &
setxkbmap -model abnt2 -layout br &
xcompmgr -n -C &
xrdb $HOME.Xresources &
xbindkeys --poll-rc &
wmname LG3D 


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 2
bspc config normal_border_color "#408522"
bspc config focused_border_color "#30cc30"

bspc config split_ratio          0.45
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 15

bspc rule -a "*" split_dir=weast
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a discord desktop='4' follow=on state=floating rectangle=1200x900+0+0 center=true
bspc rule -a kitty # state=pseudo_tiled rectangle=900x600+0+0
bspc rule -a spotify desktop='7' follow=off
bspc rule -a xfe state=floating
bspc rule -a jetbrains-studio state=floating follow=off desktop=^5 manage=on
bspc rule -a termite state=floating
#bspc rule -a XTerm state=fullscreen
bspc rule -a feh state=floating border=off
bspc rule -a Steam desktop='9'
