#! /bin/sh
$HOME/.config/polybar/launch.sh & 
feh --bg-fill $HOME/Pictures/Wallpapers/wallpaper.jpg & 
setxkbmap -model abnt2 -layout br &
sxhkd > $HOME/.config/sxhkd/sxhkd.log &
xcompmgr -n &
wmname LG3D &
xrdb $HOME/.Xresources &
xsetroot -cursor_name left_ptr &
xbindkeys --poll-rc


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           7
bspc config normal_border_color  "#a200ff"
bspc config focused_border_color "#00ffd0"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 30

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='4' follow=on 
bspc rule -a spotify desktop='4' follow=on
bspc rule -a xfe state=floating
bspc rule -a jetbrains-studio state=floating follow=off desktop=^5 manage=on
bspc rule -a guitarix state=floating follow=off desktop=^5 manage=on
bspc rule -a termite state=floating
bspc rule -a Steam follow=on desktop='9' floating=on manage=on
bspc rule -a Code follow=off focus=on desktop='^2' state=pseudo-tiled
bspc rule -a XTerm state=fullscreen
bspc rule -a feh state=floating border=off
